### ISSUE TITLE
Error when file is on SD card

### ISSUE THREAD

**Issue by cyberreefguru** [marian42/octoprint-preheat#5]
I just installed the plug in but when i select preheat using a file on the SD card, I get an internal error on the UI.  The logs say:

2017-11-25 21:28:49,825 - octoprint - ERROR - Exception on /api/plugin/preheat [POST]
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/OctoPrint-1.3.5-py2.7.egg/octoprint/server/util/flask.py", line 1111, in decorated_view
    return flask.ext.login.login_required(func)(*args, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/Flask_Login-0.2.2-py2.7.egg/flask_login.py", line 637, in decorated_view
    return func(*args, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/OctoPrint-1.3.5-py2.7.egg/octoprint/server/api/__init__.py", line 99, in pluginCommand
    response = api_plugin.on_api_command(command, data)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_preheat/__init__.py", line 101, in on_api_command
    self.preheat()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_preheat/__init__.py", line 90, in preheat
    temperatures = self.get_temperatures()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_preheat/__init__.py", line 59, in get_temperatures
    file = open(path_on_disk, 'r')
IOError: [Errno 2] No such file or directory: u'/home/pi/.octoprint/uploads/enclos-1.gco'
2017-11-25 21:28:51,293 - tornado.access - ERROR - 500 POST /api/plugin/preheat (127.0.0.1) 2934.47ms

Looks like the plugin is pulling from uploads not the SD card.  I'm not sure where "path_on_disk" is defined; I'll have to dig into the code later.

-Tom

**Comment by marian42** [comment]
I just looked into that. Apparently it is not possible to read files from the SD card. I will add a feature to heat to a predefined temperature in that case.
