### ISSUE TITLE
BUG: Throws error "Can't set the temperature because the printer is not ready."

### ISSUE THREAD

**Issue by puterboy** [marian42/octoprint-preheat#62]
Octoprint.log shows the following error:
```
2024-01-28 16:12:27,184 - octoprint.plugin - ERROR - Error while calling plugin preheat
Traceback (most recent call last):
  File "/home/kosowsky/octoprint/venv/lib/python3.11/site-packages/octoprint/plugin/__init__.py", line 275, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kosowsky/octoprint/venv/lib/python3.11/site-packages/octoprint/util/__init__.py", line 1686, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/kosowsky/octoprint/venv/lib/python3.11/site-packages/octoprint_preheat/__init__.py", line 367, in on_event
    self.preheat(file_name=payload["path"])
  File "/home/kosowsky/octoprint/venv/lib/python3.11/site-packages/octoprint_preheat/__init__.py", line 318, in preheat
    self.check_state()
  File "/home/kosowsky/octoprint/venv/lib/python3.11/site-packages/octoprint_preheat/__init__.py", line 231, in check_state
    raise PreheatError("Can't set the temperature because the printer is not ready.")
octoprint_preheat.PreheatError: Can't set the temperature because the printer is not ready.
```

While the error is seemingly harmless, it would be nice to catch this excpetion in the code rather than throwing an ugly python error in the log

**Comment by puterboy** [comment]
Any progress on this????
